# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys
import webbrowser
import configparser

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow

import file_test

config = configparser.ConfigParser()
config.read("config.ini")
reg_cap = config.get("SETTING", "reg_cap").lower() == "true"
allow_cover = config.get("SETTING", "allow_cover").lower() == "true"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label.setObjectName("label")
        self.root_path_text = QtWidgets.QLineEdit(self.splitter)
        self.root_path_text.setObjectName("root_path_text")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_2.setObjectName("label_2")
        self.ext_text = QtWidgets.QLineEdit(self.splitter)
        self.ext_text.setMaximumSize(QtCore.QSize(160, 16777215))
        self.ext_text.setObjectName("ext_text")
        self.pushButton = QtWidgets.QPushButton(self.splitter)
        self.pushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setMinimumSize(QtCore.QSize(0, 45))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_3 = QtWidgets.QLabel(self.splitter_2)
        self.label_3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_3.setObjectName("label_3")
        self.key_text = QtWidgets.QLineEdit(self.splitter_2)
        self.key_text.setMaximumSize(QtCore.QSize(180, 16777215))
        self.key_text.setObjectName("key_text")
        self.label_4 = QtWidgets.QLabel(self.splitter_2)
        self.label_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_4.setObjectName("label_4")
        self.filter_text = QtWidgets.QLineEdit(self.splitter_2)
        self.filter_text.setMaximumSize(QtCore.QSize(240, 16777215))
        self.filter_text.setText("")
        self.filter_text.setObjectName("filter_text")
        self.reg_cap_btn = QtWidgets.QCheckBox(self.splitter_2)
        self.reg_cap_btn.setMinimumSize(QtCore.QSize(0, 20))
        self.reg_cap_btn.setMaximumSize(QtCore.QSize(160, 16777215))
        self.reg_cap_btn.setObjectName("reg_cap_btn")
        self.allow_cover_btn = QtWidgets.QCheckBox(self.splitter_2)
        self.allow_cover_btn.setMaximumSize(QtCore.QSize(180, 16777215))
        self.allow_cover_btn.setObjectName("allow_cover_btn")
        self.auto_result_btn = QtWidgets.QCheckBox(self.splitter_2)
        self.auto_result_btn.setChecked(True)
        self.auto_result_btn.setObjectName("auto_result_btn")
        self.gridLayout.addWidget(self.splitter_2, 1, 0, 1, 1)
        self.result_text = QtWidgets.QTextEdit(self.centralwidget)
        self.result_text.setObjectName("result_text")
        self.gridLayout.addWidget(self.result_text, 2, 0, 1, 1)
        self.result_text.raise_()
        self.splitter.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.analyze)

    def analyze(self):
        try:
            self.root_dir = self.root_path_text.text()
            self.key = self.key_text.text().strip()
            self.filter = self.filter_text.text().strip()
            self.ext = self.ext_text.text().strip()
            self.ignore_cap = self.reg_cap_btn.isChecked()
            self.allow_cover = self.allow_cover_btn.isChecked()
            self.auto_result = self.auto_result_btn.isChecked()
            result = list(file_test.analyze(self.root_dir, self.key, self.ext,self.filter, self.ignore_cap, self.allow_cover))
            result.append(self.key)
            all_time, count, result_file_name, key = [f" <b>{i}</b> " for i in result]
            self.result_text.setText(f"[+]分析关键词{key}完毕，用时{all_time}s，共有{count}条匹配数据，结果保存在{result_file_name}文件中")
            if self.auto_result:
                webbrowser.open(f"file:\\\\{os.getcwd()}\\{result[2]}")
        except Exception as e:
            self.result_text.append(f"[-]分析异常，异常详情：<b>{str(e)}</b>")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "代码分析工具"))
        self.label.setText(_translate("MainWindow", "根路径"))
        self.label_3.setText(_translate("MainWindow", "查找"))
        self.label_4.setText(_translate("MainWindow", "过滤"))
        self.label_2.setText(_translate("MainWindow", "扩展名"))
        self.pushButton.setText(_translate("MainWindow", "确认"))
        self.reg_cap_btn.setText(_translate("MainWindow", "匹配大小写"))
        self.allow_cover_btn.setText(_translate("MainWindow", "覆盖结果文件"))
        self.auto_result_btn.setText(_translate("MainWindow", "自动打开结果文件"))


if __name__ == '__main__':
    app = QApplication(sys.argv)  # 初始化app
    MainWindow = QMainWindow()  # 创建主窗口
    ui = Ui_MainWindow()  # 创建UI界面
    ui.setupUi(MainWindow)  # 初始化UI到主窗口，主要是建立代码与ui之间的signal与slot
    MainWindow.show()  # 显示窗口
    sys.exit(app.exec_())  # 消息循环结束之后返回0，接着调用sys.exit(0)退出程序